### ISSUE TITLE
MyPassPlus at OpenAPK

### ISSUE THREAD

**Issue by mobilenetworkltd** [rodolfo-verde/MyPassPlus#1]
Hey,

First of all, kudos for the great work at MyPassPlus app ! 

I’m George, me and a friend of mine we run the OpenAPK.net site, which is kind of a repo for open source apps for Android. We list and follow thousands of foss apps and served almost a million downloads last month. 

OpenAPK is a spinoff of the AndroidFreeware.net website, which is one of the oldest and most trusted places to download free apps for Android with no security compromise.

I’ve listed MyPassPlus on both sites (https://www.openapk.net/mypassplus/com.rfvc.mypassplus/ , https://www.androidfreeware.net/download-mypassplus-apk.html) please review the listings and let me know if we need to add some additional info. The listings are hooked to your Github repository, so every time you update your app the download links will point to the latest release. We do not store or vet the APK files in any way to ensure the security of our visitors.

One of our editors have written a review of the MyPassPlus app, explaining the main features in detail and translated it to more than 15 languages.

If you are interested you can link to it and use our download badge ( https://www.openapk.net/images/openapk-badge.png  and https://www.androidfreeware.net/images/androidfreeware-badge.png)

![openapk-badge-2](https://github.com/user-attachments/assets/d722c50a-4345-48a9-9aa4-8a9a54a4c982)

![androidfreeware-badge](https://github.com/user-attachments/assets/33057012-0485-4cd5-981f-2ff5811e10f4)

**Comment by rodolfo-verde** [comment]
Hi George,

Thank you for reaching out and for featuring MyPassPlus on both OpenAPK.net and AndroidFreeware.net. I really appreciate the effort you and your team have put into supporting open-source apps and providing a platform to help them reach a wider audience.

I’ve reviewed the listings you shared. Everything looks great so far! The automated update feature hooked to the GitHub repository is a fantastic addition. 

I’ve also added the download badges to the project’s README to make it easier for users to access these platforms. Thanks for providing them—they look great and make the project more user-friendly!

If I notice anything that needs adjustments in the future, I’ll be sure to let you know. Thanks again for supporting open-source software and for showcasing MyPassPlus!

Best regards,
Rodolfo Verde
